### ISSUE TITLE
ValueError: max() arg is an empty sequence with dlldiag trace

### ISSUE THREAD

**Issue by fohrloop** [adamrehn/dll-diagnostics#1]
Hello,

I tried the `dlldiag trace`  in an virtual environment, trying to analyze the `python.exe`:

```
dlldiag trace .\venv\Scripts\python.exe
```

But it first shows an popup (failed to set registry value)

![image](https://user-images.githubusercontent.com/17479683/100483861-fbda1080-3102-11eb-96df-f4d10747e972.png)

and then gives following traceback:

```python

Summary of LdrLoadDll calls:
Traceback (most recent call last):
  File "C:\myproj\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\myproj\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\myproj\venv\Scripts\dlldiag.exe\__main__.py", line 9, in <module>
  File "c:\myproj\venv\lib\site-packages\dlldiag\main.py", line 29, in main
    subcommands[subcommand]['function']()
  File "c:\myproj\venv\lib\site-packages\dlldiag\subcommands\trace.py", line 247, in trace
    OutputFormatting.printRows(summary, spacing=4)
  File "c:\myproj\venv\lib\site-packages\dlldiag\common\OutputFormatting.py", line 59, in printRows
    width = max([len(row[0]) for row in rows]) + spacing
ValueError: max() arg is an empty sequence
```

### Setup
- Python 3.7.7rc1 32-bit (WinPython)
- WinDbg 10.0.19041.1 
- Windows 10 64-bit
- dll-diagnostics 0.0.3

### Additional info

The 
```
dlldiag deps .\venv\Scripts\python.exe
```

works fine.

The error popup comes from the `dlldiag\common\WindowsDebugger.py` line:

```python
            subprocess.run(
                [
                    join(self._debuggers[architecture], "gflags.exe"),
                    "-i",
                    basename(executable),
                    "+sls",
                ],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=True,
            )
```

when the first argument for `run()` is

```
['C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x86\\gflags.exe',
 '-i',
 'dlldiag-helper-loadlibrary.exe',
 '+sls']
```

just before running the `run()`, the variables in the local scope and the `sys.path` is:

```
In [18]: sys.path
Out[18]:
['C:\\myproj\\venv\\Scripts\\dlldiag.exe',
 'C:\\myproj\\python\\python37.zip',
 'C:\\myproj\\python\\DLLs',
 'C:\\myproj\\python\\lib',
 'C:\\myproj\\python',
 'c:\\myproj\\venv',
 'c:\\myproj\\venv\\lib\\site-packages',
 'c:\\myproj\\venv\\lib\\site-packages\\win32',
 'c:\\myproj\\venv\\lib\\site-packages\\win32\\lib',
 'c:\\myproj\\venv\\lib\\site-packages\\Pythonwin',
 'c:\\myproj\\venv\\lib\\site-packages\\IPython\\extensions']

In [19]: args
Out[19]: ['C:\\myproj\\venv\\Scripts\\python.exe']

In [20]: executable
Out[20]: 'c:\\myproj\\venv\\lib\\site-packages\\dlldiag\\bin\\x86\\dlldiag-helper-loadlibrary.exe'

In [21]: cwd
Out[21]: 'C:\\myproj\\venv\\Scripts'
```

**Comment by adamrehn** [comment]
I've fixed the handling of zero-length `rows` arrays in `OutputFormatting.printRows()` in commit 873a68d, but I'm a bit confused as to the behaviour that you're seeing with respect to `gflags.exe`. In every version of WinDbg that I've tested (including 10.0.19041.1), failures that occur when invoking `gflags.exe` from the command-line are reported in the command-line output only (no GUI dialog box), and result in a non-zero exit code that is detected by dlldiag and then propagated to the user with an error message indicating that loader snaps could not be enabled due to insufficient privileges. Are you sure the dialog box popup is being generated by `gflags.exe` and not by `dlldiag-helper-loadlibrary.exe` when it attempts to call `LoadLibraryW()` on the Python executable?

**Comment by fohrloop** [comment]
### Tests with master branch version of dll-diagnostics 

I tried with the newest changes by installing dll-diagnostics with pip straight from the github master branch, including the commit https://github.com/adamrehn/dll-diagnostics/commit/873a68dbded6b8103f7be1e1970153c530f1f459. Now it said:

```
(test) PS C:\tmp\testing> dlldiag trace C:\Python\venvs\test\Scripts\python.exe
DLL Diagnostic Tools version 0.0.3
Copyright (c) 2019 Adam Rehn

Parsing module header and detecting architecture... done.

Identifying the module's delay-loaded dependencies... done.

Parsed module details:
Module:          C:\Python\venvs\test\Scripts\python.exe
Type:            Executable
Architecture:    x64

The module imports 0 delay-loaded dependencies:


Error: cannot run the helper executable for architecture x64. Please ensure the Microsoft Visual C++ Redistributable for Visual Studio 2015-2019 is installed correctly.
```

Then, I installed the [Microsoft Visual C++ Redistributable for Visual Studio 2015-2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) (`vc_redist.x64.exe`) and rebooted. Got the same error.  The error is arising in `subcommands\trace.py` since `helper.canRun() == False`.  This in turn is happening since in `common\HelperProcess.py:HelperProcess.canRun`, the `self.executable` is

```
In [1]: self.executable
Out[1]: 'c:\\python\\venvs\\test\\lib\\site-packages\\dlldiag\\bin\\x64\\dlldiag-helper-loadlibrary.exe'
```

There is no `bin` folder in `C:\Python\venvs\test\Lib\site-packages\dlldiag`. 

### Tests with dll-diagnostics 0.0.3

Tried to run again

```
dlldiag trace C:\Python\venvs\test\Scripts\python.exe
```

and then I get the same error message as in the original post.  It happens at `common\WindowsDebugger.py:WindowsDebugger.debugWithLoaderSnaps` at lines

```python
subprocess.run(
	[
		join(self._debuggers[architecture], "gflags.exe"),
		"-i",
		basename(executable),
		"+sls",
	],
	stdout=subprocess.DEVNULL,
	stderr=subprocess.DEVNULL,
	check=True,
)
```

The `executable` is `c:\python\venvs\test\lib\site-packages\dlldiag\bin\x64\dlldiag-helper-loadlibrary.exe` which is found on the filesystem.

**Comment by adamrehn** [comment]
Regarding the tests with the master branch: you will need to run the [build-helpers.py](https://github.com/adamrehn/dll-diagnostics/blob/v0.0.4/build-helpers.py) script to compile the helper C++ executables if you are installing the package from source rather than a pre-built wheel.

It occurs to me that you are attempting to perform a trace for a 64-bit executable file whilst using a 32-bit Python installation to run dlldiag itself. Although in theory this should work fine (the entire purpose of including both 32-bit and 64-bit helper executables is to ensure cross-compatibility), I've only ever actually tested dlldiag using a 64-bit version of the Python interpreter. I wonder if the underlying problem is something unique to 32-bit Python that I've not accounted for?

**Comment by fohrloop** [comment]
Oh yeah, of course there will be no binaries if I install the package from the github source! 

I reinstalled `dll-diagnostics`, and pip installed the version 0.0.4. I also ran the 

```
dlldiag trace C:\Python\venvs\test\Scripts\python.exe
```
in an elevated shell. I worked just fine. The strange thing is that now I cannot reproduce the problem anymore, even if I install v.0.0.3 and run inside non-elevated shell (it will show the popup "Failed to set registry value" if the shell is not elevated, though).  Hard to say where the problem was but at least everything works with v.0.0.4, inside elevated shell, when `vc_redist.x64.exe` is installed:

```
(test) PS C:\tmp\testing> dlldiag trace C:\Python\venvs\test\Scripts\python.exe
DLL Diagnostic Tools version 0.0.4
Copyright (c) 2019 Adam Rehn

Parsing module header and detecting architecture... done.

Identifying the module's delay-loaded dependencies... done.

Parsed module details:
Module:          C:\Python\venvs\test\Scripts\python.exe
Type:            Executable
Architecture:    x64

The module imports 0 delay-loaded dependencies:


Performing LoadLibrary() trace for C:\Python\venvs\test\Scripts\python.exe...
Done.

Summary of LdrLoadDll calls:
C:\Python\venvs\test\Scripts\python.exe    Loaded successfully

Summary of LdrpLoadDllInternal calls:
C:\Python\venvs\test\Scripts\python.exe    Loaded successfully

Summary of LdrpMinimalMapModule calls:
C:\Python\venvs\test\Scripts\python.exe    Mapped successfully

Summary of LdrpResolveDllName calls:
python.exe    C:\Python\venvs\test\Scripts\python.exe
```
